AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Birdtag application data resources (DynamoDB).

Resources:
  FileMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FileMetadata
      AttributeDefinitions:
        - AttributeName: fileId
          AttributeType: S
      KeySchema:
        - AttributeName: fileId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  FileMetadataTableName:
    Description: Name of the DynamoDB table for Birdtag results.
    Value: !Ref FileMetadataTable
    Export:
      Name: FileMetadataTableName 
